### ISSUE TITLE
Model tests generated via validation do not respect :if conditions

### ISSUE THREAD

**Issue by sha1sum** [ndea/regressor#10]
Given the following model validation:

``` ruby
validates :hair_color, presence: true, if: :has_hair?
```

... the automatically generated model spec:

``` ruby
it { is_expected.to validate_presence_of :hair_color }
```

... fails if there is no initial value for `has_hair?` or if the initialized value of `has_hair?` is false.

**Comment by erwinjunker** [comment]
Hi,
yeah conditional validations are not supported at the moment. 
I will try to add them asap.

**Comment by sha1sum** [comment]
If you can find the condition method from the options hash then you may be able to mock them out. I also failed to mention that `unless` conditions may occasionally do the same thing if I'm thinking about this correctly.

**Comment by erwinjunker** [comment]
Yes that should do the trick. Thanks!
