### ISSUE TITLE
"error  mongoid [not found]"

### ISSUE THREAD

**Issue by sha1sum** [ndea/regressor#15]
Even after updating the gem to the github-hosted version, upon trying to generate _any_ migration, the generator fails with

```
ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /opt/code/salescenter/bin/spring rails generate migration SomeMigration -s
       error  mongoid [not found]
```

It's worth noting that we do not use anything backed with mongoid in our application.

**Comment by erwinjunker** [comment]
Could you try that again not using spring? Experienced some issues related to loading of spring.

**Comment by sha1sum** [comment]
No joy. Stopping spring did not fix the issue :(

**Comment by erwinjunker** [comment]
I removed the mongoid-rspec dependency from the gemspec can you try generating using the 0.5.7 version of regressor?

**Comment by sha1sum** [comment]
_Perfect!_ Thank you!
