### ISSUE TITLE
web-console gem (ships with Rails 4.2) causing filter failures

### ISSUE THREAD

**Issue by sha1sum** [ndea/regressor#19]
When using the web-console gem, it apparently uses an automatically-inserted after_filter in every controller. This apparently only happens when the gem is loaded only into the development environment, but loading this particular gem into the development environment makes sense and is indicated as such in [the instructions](https://github.com/rails/web-console).

Failure/Error: it { should use_after_filter(:inject_console_into_view) }
       Expected that MyController would have :inject_console_into_view as a after_filter

**Comment by erwinjunker** [comment]
I guess the web-console gem is also not in the test group of the gemfile. 
Is it possible to call a rails generator with the test environment?

**Comment by sha1sum** [comment]
Running the `regressor:controller` generator in the `test` environment did indeed skip the broken filters.
