### ISSUE TITLE
explicitly add gem 'shoulda-matchers' to Gemfile

### ISSUE THREAD

**Issue by spaghetticode** [ndea/regressor#2]
In order to make tests pass I had to explicitly list the shoulda-matchers gem in the Gemfile. Typical errors were something like:

```
undefined method `belong_to' for #<RSpec::ExampleGroups::Address_2:0x00000102255a00>
expected #<Address:0x00000108e3fd88> to respond to `has_db_column?`
```

Nice project indeed, thanks for sharing!

**Comment by erwinjunker** [comment]
Which version of shoulda-matchers do you use?
I added following dependency to the gemspec:

``` ruby
  s.add_dependency "shoulda-matchers", ">= 2.7.0"
```

I will try to fix this issue later this day.

Nice project indeed, thanks for sharing!
 -- Thanks! :+1:

**Comment by spaghetticode** [comment]
The shoulda-matchers gem which was bundle on my machine is 2.8.0

**Comment by erwinjunker** [comment]
Added shoulda-matchers as a runtime dependency. 
It should work now without having shoulda-matchers defined in the Gemfile.

**Comment by erwinjunker** [comment]
Have put following line to the rails_helper.rb?

``` ruby
require 'shoulda/matchers'
```

**Comment by spaghetticode** [comment]
No I didn't, as per the updated readme it should necessary only for rspec 2.x, I was using 3.2

Later I will check if now it works fine with the `add_dependecy` addition and let you know.

**Comment by spaghetticode** [comment]
No way, I updated the gem version but I still need to add `gem 'shoulda-matchers'`. No big issue though ;-)
