### ISSUE TITLE
Cannot create model regression tests

### ISSUE THREAD

**Issue by betogrun** [ndea/regressor#23]
Hi,

I'm facing the error messages bellow when I try to generate regression tests for my models:

```
$ RAILS_ENV=test rails generate regressor:model

Cannot create model regression for ApplicationRecord. Reason Could not find table ''
Cannot create model regression for User. Reason Could not find table 'users'
Cannot create model regression for Note. Reason Could not find table 'notes'
```
 
Have you seen this error before?

PS: For database I'm using sqlite.

**Comment by erwinjunker** [comment]
Hi,

did you migrated your database before running regressor?

Best regards
Erwin

**Comment by betogrun** [comment]
Hi,

That was the problem.
It is working now! 

Thanks!
